resources:
  repositories:
    - repository: catalog
      type: git
      name: TADAP-ACPDA/geonetwork-catalog

pool:
  name: tadap-dev
  demands: maven

steps:
  - checkout: self
    clean: true
  - checkout: catalog
    submodules: recursive
  - script: ls $(Build.SourcesDirectory)
